title: "Taiba Abid"
description: "Graduate student in Logic, Computation, & Methodology in CMU"
author: ""
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
url: "https://spec-b.github.io/"
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - jekyll-include-cache
  
header_pages:
  - about.md 

keep_files:
 - git 

sidebar:
  nav: "main"  # Ensures sidebar navigation works
  title: "Taiba"
  #image: "/assets/images/profile.jpg"  # Add your picture here
  description: |
    Student at CMU  
    Logic, Type Theory, Formal Epistemology  
    [tabid@andrew.cmu.edu](mailto:tabid@andrew.cmu.edu)
    personal: [taiba3abid@gmail.com](mailto:taiba3abid@gmail.com)
