title: "Taiba Abid"
description: "Graduate student in Logic, Computation, & Methodology in CMU"
author: ""
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
url: "https://spec-b.github.io/"
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - jekyll-include-cache
header_pages:
  - about.md 

include: 
 - _pages

keep_files:
 - git 

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
