#cbtaibtitle: "Taiba Abid"
locale                   : "en-US"
title                    : "About"
title_separator          : "-"
name                     : &name "Taiba Abid"
description: "Graduate student in Logic, Computation, & Methodology in CMU"
author: ""
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
baseurl: ""
url: "https://spec-b.github.io/"
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - jekyll-include-cache

minimal_mistakes_skin: "default"
custom_css:
  - "assets/css/custom.css"
  
header_pages:
  - about.md 

# Site Author
author:
  name             : "Taiba Abid"
  #avatar           : "profile.png"
  bio              : "Graduate Student"
  location         : "Pittsburgh, PA, USA"
  employer         : "Carnegie Mellon University"
  pubmed           :
  #googlescholar    : 
  email            : "specbtaiba@gmail.com"
  researchgate     :  # example: "https://www.researchgate.net/profile/yourprofile"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "spec-b"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      :
  lastfm           :
  linkedin         :
  #orcid            : 
  pinterest        :
  #soundcloud       : 
  stackoverflow    : 
  steam            :
  tumblr           :
  #twitter          : 
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :


keep_files:
 - git 

include:
  - _pages

encoding: UTF-8
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

sidebar:
  nav: "main"  # Ensures sidebar navigation works
  title: "Taiba"
  #image: "/assets/images/profile.jpg"  # Add your picture here
  description: |
    Student at CMU  
    Logic, Type Theory, Formal Epistemology  
    [tabid@andrew.cmu.edu](mailto:tabid@andrew.cmu.edu)
    personal: [specbtaiba@gmail.com](mailto:specbtaiba@gmail.com)

